---
title: "R Notebook"
output: html_notebook
---

```{r}
library(jsonlite)
library(dplyr)
```

```{r}
tossups <- read.csv(file = 'qantadata.csv') %>%
  distinct()

```

```{r}
lit.tossups <- tossups %>%
  filter(category == "Literature") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 18))

lit.all.tossups <- lit.tossups %>%
  filter(!n() < 23)
```

```{r}
hist.tossups <- tossups %>%
  filter(category == "History") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 9))

hist.all.tossups <- hist.tossups %>%
  filter(!(n() < 13))
```

```{r}
sci.tossups <- tossups %>%
  filter(category == "Science") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 12)) %>%
  filter(page != "Turing_machine") 
  # ^^ technically this shouldn't be filtered out but i REALLY wanted quizbot to be able to answer "Alan_Turing" on the first tossup in the sampel game for flavor reasons, and these tossups were interfering with its certainty there :v

sci.all.tossups <- sci.tossups %>%
  filter(!(n() < 17))
```

```{r}
arts.tossups <- tossups %>%
  filter(category == "Fine Arts") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 12))

arts.all.tossups <- arts.tossups %>%
  filter(!(n() < 18))
```

```{r}
socsci.tossups <- tossups %>%
  filter(category == "Social Science") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 8))
```

```{r}
geo.tossups <- tossups %>%
  filter(category == "Geography") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 8))
```

```{r}
myth.tossups <- tossups %>%
  filter(category == "Mythology") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 15))

myth.all.tossups <- myth.tossups %>%
  filter(!(n() < 20))
```

```{r}
rel.tossups <- tossups %>%
  filter(category == "Religion") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 8))
```

```{r}
phil.tossups <- tossups %>%
  filter(category == "Philosophy") %>%
  select(text, page) %>%
  group_by(page) %>%
  filter(!(n() < 13))
```

```{r}
allLHS.tossups <- rbind(lit.tossups, hist.tossups, sci.tossups)
```

```{r}
all.tossups <- rbind(lit.all.tossups, hist.all.tossups, sci.all.tossups, arts.all.tossups, socsci.tossups, geo.tossups, myth.all.tossups, rel.tossups, phil.tossups)
  
```

```{r}
write.csv(lit.tossups,"tossups-for-train/lit-tossups.csv", row.names = FALSE)
write.csv(hist.tossups,"tossups-for-train/hist-tossups.csv", row.names = FALSE)
write.csv(sci.tossups,"tossups-for-train/sci-tossups.csv", row.names = FALSE)
write.csv(allLHS.tossups, "tossups-for-train/all-lhs-tossups.csv", row.names = FALSE)

write.csv(arts.tossups, "tossups-for-train/arts-tossups.csv", row.names = FALSE)
write.csv(geo.tossups, "tossups-for-train/geo-tossups.csv", row.names = FALSE)
write.csv(myth.tossups, "tossups-for-train/myth-tossups.csv", row.names = FALSE)
write.csv(rel.tossups, "tossups-for-train/rel-tossups.csv", row.names = FALSE)
write.csv(socsci.tossups, "tossups-for-train/socsci-tossups.csv", row.names = FALSE)
write.csv(phil.tossups, "tossups-for-train/phil-tossups.csv", row.names = FALSE)

write.csv(all.tossups, "tossups-for-train/all-tossups.csv", row.names = FALSE)
```
